### ISSUE TITLE
Windows build fails with actions-rust-lang/setup-rust-toolchain@v2.0.0

### ISSUE THREAD

**Issue by 0xdea** [idalib-rs/idalib#81]
The Windows build fails following modifications introduced by https://github.com/0xdea/rhabdomancer/pull/12/. The culprit is the upgrade to [actions-rust-lang/setup-rust-toolchain@v2.0.0](https://github.com/actions-rust-lang/setup-rust-toolchain/releases/tag/v2.0.0). This can be solved by silencing linker warnings or by allowing cargo build warnings. However, I think the warning themselves might be of interest:

```
##[debug]Evaluating condition for step: 'build'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: build
##[debug]Loading inputs
##[debug]Loading env
Run cargo build --locked
##[debug]C:\Program Files\PowerShell\7\pwsh.EXE -command ". 'D:\a\_temp\10ca487d-225e-4206-9425-cc52998c4f94.ps1'"
    Updating crates.io index
   Compiling rhabdomancer v0.10.1-alpha (D:\a\rhabdomancer\rhabdomancer)
warning: rhabdomancer@0.10.1-alpha: IDA installation not found, check your IDADIR env var
warning: linker stdout: libidalib_sys-095ac95b3342d1ef.rlib(b8f6df7a68314fbf-gen0.o) : error LNK2019: unresolved external symbol "public: int __cdecl func_t::compare(class func_t const &)const " (?compare@func_t@@QEBAHAEBV1@@Z) referenced in function "int __cdecl func_t_compare_autocxx_wrapper_0x252280bb1934a949(class func_t const &,class func_t const &)" (?func_t_compare_autocxx_wrapper_0x252280bb1934a949@@YAHAEBVfunc_t@@0@Z)␍
         libidalib_sys-095ac95b3342d1ef.rlib(b8f6df7a68314fbf-gen0.o) : error LNK2019: unresolved external symbol "private: bool __cdecl gdl_graph_t::path(class node_set_t &,int,int)const " (?path@gdl_graph_t@@AEBA_NAEAVnode_set_t@@HH@Z) referenced in function "public: bool __cdecl gdl_graph_t::path_exists(int,int)const " (?path_exists@gdl_graph_t@@QEBA_NHH@Z)␍
         libidalib_sys-095ac95b3342d1ef.rlib(b8f6df7a68314fbf-gen0.o) : error LNK2019: unresolved external symbol "public: void __cdecl gdl_graph_t::gen_gdl(struct _iobuf *)const " (?gen_gdl@gdl_graph_t@@QEBAXPEAU_iobuf@@@Z) referenced in function cxxbridge1$199$gdl_graph_t$gen_gdl␍
         libidalib_sys-095ac95b3342d1ef.rlib(b8f6df7a68314fbf-gen0.o) : error LNK2019: unresolved external symbol "public: void __cdecl gdl_graph_t::gen_gdl(char const *)const " (?gen_gdl@gdl_graph_t@@QEBAXPEBD@Z) referenced in function cxxbridge1$199$gdl_graph_t$gen_gdl1␍
         libidalib_sys-095ac95b3342d1ef.rlib(b8f6df7a68314fbf-gen0.o) : error LNK2019: unresolved external symbol "public: void __cdecl gdl_graph_t::gen_dot(struct _iobuf *)const " (?gen_dot@gdl_graph_t@@QEBAXPEAU_iobuf@@@Z) referenced in function cxxbridge1$199$gdl_graph_t$gen_dot␍
         libidalib_sys-095ac95b3342d1ef.rlib(b8f6df7a68314fbf-gen0.o) : error LNK2019: unresolved external symbol "public: void __cdecl gdl_graph_t::gen_dot(char const *)const " (?gen_dot@gdl_graph_t@@QEBAXPEBD@Z) referenced in function cxxbridge1$199$gdl_graph_t$gen_dot1␍
         libidalib_sys-095ac95b3342d1ef.rlib(b8f6df7a68314fbf-gen0.o) : error LNK2019: unresolved external symbol "public: int __cdecl segment_t::compare(class segment_t const &)const " (?compare@segment_t@@QEBAHAEBV1@@Z) referenced in function "int __cdecl segment_t_compare_autocxx_wrapper_0x252280bb1934a949(class segment_t const &,class segment_t const &)" (?segment_t_compare_autocxx_wrapper_0x252280bb1934a949@@YAHAEBVsegment_t@@0@Z)␍
         libidalib_sys-095ac95b3342d1ef.rlib(b8f6df7a68314fbf-gen0.o) : error LNK2019: unresolved external symbol "public: __cdecl cexpr_t::cexpr_t(class mba_t *,class lvar_t const &)" (??0cexpr_t@@QEAA@PEAVmba_t@@AEBVlvar_t@@@Z) referenced in function "void __cdecl cexpr_t_new2_autocxx_wrapper_0x252280bb1934a949(struct cexpr_t *,class mba_t *,class lvar_t const &)" (?cexpr_t_new2_autocxx_wrapper_0x252280bb1934a949@@YAXPEAUcexpr_t@@PEAVmba_t@@AEBVlvar_t@@@Z)␍
         libidalib_sys-095ac95b3342d1ef.rlib(b8f6df7a68314fbf-gen0.o) : error LNK2019: unresolved external symbol "public: bool __cdecl cexpr_t::like_boolean(void)const " (?like_boolean@cexpr_t@@QEBA_NXZ) referenced in function cxxbridge1$199$cexpr_t$like_boolean␍
         libidalib_sys-095ac95b3342d1ef.rlib(b8f6df7a68314fbf-gen0.o) : error LNK2019: unresolved external symbol "public: bool __cdecl cexpr_t::is_aliasable(void)const " (?is_aliasable@cexpr_t@@QEBA_NXZ) referenced in function "bool __cdecl cexpr_t_is_aliasable_autocxx_wrapper_0x252280bb1934a949(struct cexpr_t const &)" (?cexpr_t_is_aliasable_autocxx_wrapper_0x252280bb1934a949@@YA_NAEBUcexpr_t@@@Z)␍
         libidalib_sys-095ac95b3342d1ef.rlib(b8f6df7a68314fbf-gen0.o) : error LNK2019: unresolved external symbol "public: bool __cdecl cexpr_t::is_value_used(struct citem_t const *)const " (?is_value_used@cexpr_t@@QEBA_NPEBUcitem_t@@@Z) referenced in function cxxbridge1$199$cexpr_t$is_value_used␍
         libidalib_sys-095ac95b3342d1ef.rlib(b8f6df7a68314fbf-gen0.o) : error LNK2019: unresolved external symbol "public: struct cexpr_t const * __cdecl cexpr_t::find_ptr_or_array(bool)const " (?find_ptr_or_array@cexpr_t@@QEBAPEBU1@_N@Z) referenced in function cxxbridge1$199$cexpr_t$find_ptr_or_array␍
         libidalib_sys-095ac95b3342d1ef.rlib(b8f6df7a68314fbf-gen0.o) : error LNK2019: unresolved external symbol "public: void __cdecl carglist_t::print(class _qstring<char> *,struct cfunc_t const *)const " (?print@carglist_t@@QEBAXPEAV?$_qstring@D@@PEBUcfunc_t@@@Z) referenced in function "void __cdecl carglist_t_print_autocxx_wrapper_0x252280bb1934a949(struct carglist_t const &,class _qstring<char> *,struct cfunc_t const *)" (?carglist_t_print_autocxx_wrapper_0x252280bb1934a949@@YAXAEBUcarglist_t@@PEAV?$_qstring@D@@PEBUcfunc_t@@@Z)␍
         libidalib_sys-095ac95b3342d1ef.rlib(b8f6df7a68314fbf-gen0.o) : error LNK2019: unresolved external symbol "public: int __cdecl carglist_t::print(int,struct vc_printer_t &)const " (?print@carglist_t@@QEBAHHAEAUvc_printer_t@@@Z) referenced in function "int __cdecl carglist_t_print1_autocxx_wrapper_0x252280bb1934a949(struct carglist_t const &,int,struct vc_printer_t &)" (?carglist_t_print1_autocxx_wrapper_0x252280bb1934a949@@YAHAEBUcarglist_t@@HAEAUvc_printer_t@@@Z)␍
         libidalib_sys-095ac95b3342d1ef.rlib(b8f6df7a68314fbf-gen0.o) : error LNK2019: unresolved external symbol "public: void __cdecl ctry_t::print(struct citem_t const *,int,struct vc_printer_t &)const " (?print@ctry_t@@QEBAXPEBUcitem_t@@HAEAUvc_printer_t@@@Z) referenced in function "void __cdecl ctry_t_print_autocxx_wrapper_0x252280bb1934a949(struct ctry_t const &,struct citem_t const *,int,struct vc_printer_t &)" (?ctry_t_print_autocxx_wrapper_0x252280bb1934a949@@YAXAEBUctry_t@@PEBUcitem_t@@HAEAUvc_printer_t@@@Z)␍
         libidalib_sys-095ac95b3342d1ef.rlib(b8f6df7a68314fbf-gen0.o) : error LNK2019: unresolved external symbol "public: __cdecl cfunc_t::cfunc_t(class mba_t *)" (??0cfunc_t@@QEAA@PEAVmba_t@@@Z) referenced in function "void __cdecl cfunc_t_new_autocxx_autocxx_wrapper_0x252280bb1934a949(struct cfunc_t *,class mba_t *)" (?cfunc_t_new_autocxx_autocxx_wrapper_0x252280bb1934a949@@YAXPEAUcfunc_t@@PEAVmba_t@@@Z)␍
         D:\a\rhabdomancer\rhabdomancer\target\debug\deps\rhabdomancer.exe : warning LNK4088: image being generated due to /FORCE option; image may not run
  |
  = note: `#[warn(linker_messages)]` on by default

error: `rhabdomancer` (bin "rhabdomancer") generated 1 warning
warning: rhabdomancer@0.10.1-alpha: IDA installation not found, check your IDADIR env var
error: warnings are denied by `build.warnings` configuration
Error: Process completed with exit code 1.
##[debug]Finishing: build
```

**Comment by xorpse** [comment]
I recall seeing missing symbol issues when I first added support for Windows-based builds--it's why [this](https://github.com/idalib-rs/idalib/blob/71c70a04bc8d2d8531e2c6b9746440a2eb030b2d/idalib-build/src/lib.rs#L111-L116) is in place--is the issue here that warnings are now treated as errors?

**Comment by 0xdea** [comment]
Oh, I see. Yes, the issue is that linker warnings are now treated as errors. I "solved" this by silencing linker warnings as they were until some time ago.
